version: "3.8"

services:
  web:
    image: 
      jrycho/diplomka-web:latest
    command: npm run start
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.vps
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://46.28.109.229:8000
    depends_on:
      - fastapi
    restart: unless-stopped
    mem_limit: 600m

  fastapi:
    image: jrycho/diplomka-fastapi:latest  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB_NAME=nutrition_app
    depends_on:
      - mongo
    restart: unless-stopped
    mem_limit: 400m

  mongo:
    image: mongo:6

    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    mem_limit: 512m

volumes:
  mongo_data: